version: '3.9'

services:
  app:
    container_name: ${NODE_ENV}_app
    build:
      context: https://github.com/julekgwa/tuts-api.git#main
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DATABASE=${DATABASE}
      - DB_HOST=${DB_HOST}
      - NODE_ENV=${NODE_ENV}
      - DOMAIN=${DOMAIN}
      - API_URL=${API_URL}
    ports:
      - ${APP_PORT:-3000}:${PORT}
    deploy:
      replicas: 1

  nginx:
    container_name: ${NODE_ENV}_nginx
    image: nginx:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${APP_PORT}
      - DOMAIN=${DOMAIN}
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/nginx.template.conf:ro
    command: ["/bin/bash", "-c", "export NODE_ENV && export APP_PORT  && envsubst '$${NODE_ENV} $${APP_PORT} $${DOMAIN}' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
    depends_on:
      - app
