version: '3.9'

services:
  app:
    container_name: ${ENVIRONMENT}_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=${API_URL}
    ports:
      - ${APP_PORT:-3000}:${PORT}
    deploy:
      replicas: 1
  nginx:
    container_name: ${ENVIRONMENT}_nginx
    image: nginx:latest
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - APP_PORT=${APP_PORT}
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/nginx.template.conf:ro
    command: ["/bin/bash", "-c", "export ENVIRONMENT && export APP_PORT  && envsubst '$${ENVIRONMENT} $${APP_PORT}' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
    depends_on:
      - app
