openapi: 3.0.0
info:
  title: Quick Tuts API
  description: API documentation for Quick Tuts
  version: 1.0.0
servers:
  - url: /api/v1/
    description: Version 1 of the API
paths:
  /movies:
    get:
      summary: Get all movies
      tags:
        - Movies
      operationId: getMovies
      responses:
        '200':
          description: A list of movies
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Movie'
                  success:
                    type: boolean
                  message:
                    type: string
    post:
      summary: Add a new movie
      tags:
        - Movies
      operationId: addMovie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'


  /movies/{id}:
    get:
      tags:
        - Movies
      summary: Get a movie by ID
      operationId: getMovie
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the movie
          schema:
            type: string
      responses:
        '200':
          description: A movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
    put:
      tags:
        - Movies
      summary: Update a movie by ID
      operationId: updateMovie
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the movie
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMovie'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
    delete:
      tags:
        - Movies
      summary: Delete a movie by ID
      operationId: deleteMovie
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the movie
          schema:
            type: string
      responses:
        '204':
          description: No content

components:
  schemas:
    UpdateMovie:
      type: object
      properties:
        title:
          type: string
        releaseDate:
          type: string
        rating:
          type: array
          items:
            type: object
            properties:
              source:
                type: string
              value:
                type: number
        genre:
          type: array
          items:
            type: string
        director:
          type: string

    Movie:
      type: object
      properties:
        title:
          type: string
        releaseDate:
          type: string
        rating:
          type: array
          items:
            type: object
            properties:
              source:
                type: string
              value:
                type: number
        genre:
          type: array
          items:
            type: string
        director:
          type: string
      required:
        - title
        - releaseDate
        - director